################################################################################
# User-maintained build rules for files not yet generated into Debug/*.mk.
#
# CCS regenerates the general directory rules. App sources and the LineTrace
# test need the LineTrace include path before the next metadata regeneration.
################################################################################

LINE_TRACE_BUILD_INCLUDES := \
-I"../App" \
-I"../BSP/ADC" \
-I"../BSP/Board" \
-I"../BSP/Delay" \
-I"../BSP/DL1A" \
-I"../BSP/DL1B" \
-I"../BSP/SoftI2C" \
-I"../BSP/Timer" \
-I"../BSP/UART" \
-I"../Module/Beep" \
-I"../Module/Encoder" \
-I"../Module/Grayscale" \
-I"../Module/IMU" \
-I"../Module/Key5D" \
-I"../Module/Keys" \
-I"../Module/LineTrace" \
-I"../Module/Menu" \
-I"../Module/Motor" \
-I"../Module/OLED" \
-I"../Module/PID" \
-I"../Module/ToF" \
-I"../tests" \
-I"."

./App/%.o: ../App/%.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CG_TOOL_ROOT)/bin/tiarmclang.exe" -c @"device.opt" @"ccsIncludes.opt" -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -O2 $(LINE_TRACE_BUILD_INCLUDES) -gdwarf-3 -MMD -MP -MF"$(@:%.o=%.d_raw)" -MT"$@" -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

./tests/line_trace_test.o: ../tests/line_trace_test.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CG_TOOL_ROOT)/bin/tiarmclang.exe" -c @"device.opt" @"ccsIncludes.opt" -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -O2 $(LINE_TRACE_BUILD_INCLUDES) -gdwarf-3 -MMD -MP -MF"tests/line_trace_test.d_raw" -MT"$@" -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '
