#ifndef APP_APP_CONFIG_H
#define APP_APP_CONFIG_H

#define APP_KEY_SAMPLE_PERIOD_MS (10U)
#define APP_MENU_DYNAMIC_DISPLAY_PERIOD_MS (200U)

/* 旧外设模块仍参与 CCS 编译，但当前两任务固件不调度它们。 */
#define APP_KEY_TEST_DISPLAY_PERIOD_MS (100U)
#define APP_KEY_TEST_SERIAL_PERIOD_MS (200U)
#define APP_ELECTROMAGNET_KEY_PERIOD_MS (10U)
#define APP_IMU_SAMPLE_PERIOD_MS (20U)
#define APP_IMU_DIAGNOSTIC_FRAME_COUNT (5U)
#define APP_IMU_DIAGNOSTIC_PERIOD_MS (1000U)
#define APP_TOF_POLL_PERIOD_MS (50U)
#define APP_TOF_LOG_PERIOD_MS (500U)

/* 速度环、灰度外环和任务状态机统一使用 20 ms 基准周期。 */
#define APP_CONTROL_PERIOD_MS (20U)
#define APP_VEHICLE_SPEED_PERIOD_MS APP_CONTROL_PERIOD_MS
#define APP_VEHICLE_CONTROL_PERIOD_MS APP_CONTROL_PERIOD_MS
#define APP_LINE_CONTROL_PERIOD_MS APP_CONTROL_PERIOD_MS
#define APP_VOFA_TELEMETRY_PERIOD_MS (50U)

/* Task 1：平滑往返。达到设定速度后保持 3 s，再减速、停车和换向。 */
#define APP_TASK1_HOLD_TIME_MS (3000U)
#define APP_TASK1_ZERO_DWELL_MS (300U)
#define APP_TASK1_RAMP_STEP (2.0f)

/* fa2011f Task 2 停车线：起步屏蔽、里程门槛和闭环缓停时间。 */
#define APP_TASK2_CROSS_LOCKOUT_FRAMES (80U)
#define APP_TASK2_CROSS_MIN_ENC_AVG (24000U)
#define APP_TASK2_SLOW_STOP_DURATION_MS (50U)
#define APP_TASK2_ACTIVE_BRAKE_PWM_MAX (1000.0f)
#define APP_TASK2_ACTIVE_BRAKE_STEER_MAX (300.0f)
#define APP_TASK2_ACTIVE_BRAKE_STOP_SPEED (3.0f)

/* VOFA 默认值和安全范围。S 同时作为 Task 1 定速值和 Task 2 巡航速度。 */
#define APP_VEHICLE_DEFAULT_SPEED (100.0f)
#define APP_VOFA_SPEED_MAX (200.0f)
#define APP_VOFA_SPEED_PID_GAIN_MAX (200.0f)
#define APP_VOFA_LINE_KP_MAX (10.0f)

/* 灰度外环：低强度统一滤波、死区、PD、修正斜率限制和弯道降速。 */
#define APP_LINE_CENTER_DEADBAND (4)
#define APP_LINE_DEFAULT_KP (0.85f)
#define APP_LINE_FIXED_KD (0.08f)
#define APP_LINE_CURVE_SLOWDOWN_GAIN (0.30f)
#define APP_LINE_MINIMUM_SPEED_RATIO (0.45f)
#define APP_LINE_CORRECTION_MAX (30.0f)
#define APP_LINE_CORRECTION_SLEW_STEP (6.0f)

#define APP_VEHICLE_PID_OUT_MAX (1800.0f)
#define APP_VEHICLE_PID_OUT_MIN (-1800.0f)
#define APP_VEHICLE_PID_ERR_MAX (120.0f)
#define APP_VEHICLE_PID_DELTA_MAX (120.0f)

#endif
